trigger:
- master

variables:
  - group: prod-variables

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: VariablesTest
    displayName: 'Show Variable Values'
    steps:
      - script: |
          echo $SERVICECONNECTION

  - job: Build
    displayName: Build
    pool:
      vmImage: '$VMIMAGE'
    steps:
    - task: CopyFiles@2
      displayName: 'Publish ARM templates'
      inputs:
        SourceFolder: 'MyDemo.Deployments'
        Contents: '**\*.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)\deployments'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: "$workingDirectory\\*.csproj"
        arguments: --output $(System.DefaultWorkingDirectory)\publish_output --configuration Release

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)\publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)\$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)\deployments'
      artifact: deployments

    - publish: '$(Build.ArtifactStagingDirectory)\$(Build.BuildId).zip'
      artifact: drop
