trigger:
- master

variables:
  - group: prod-variables
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: VariablesTest
    displayName: 'Show Variable Values'
    steps:
      - script: |
          echo $SERVICECONNECTION

  - job: Build
    displayName: Build
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2019'
    steps:
    - task: CopyFiles@2
      displayName: 'Publish ARM templates'
      inputs:
        SourceFolder: 'MyDemo.Deployments'
        Contents: '**\*.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)\deployments'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '$(System.DefaultWorkingDirectory)/MyDemo.Functions/*.csproj'
        arguments: --output $(System.DefaultWorkingDirectory)\publish_output --configuration Release

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)\publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)\$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)\deployments'
      artifact: deployments

    - publish: '$(Build.ArtifactStagingDirectory)\$(Build.BuildId).zip'
      artifact: drop


- stage: Deploy
  displayName: Deploy stage
  dependsOn: ArmResources
  condition: succeeded()

  jobs:
  - deployment: Deploy
    variables:
      - group: prod-variables
    displayName: Deploy
    environment: 'production'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2019'

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: $SERVICECONNECTION
              subscriptionId: $AzureSubscriptionId
              action: 'Create Or Update Resource Group'
              resourceGroupName: $RESOURCEGROUP
              location: $RESOURCELOCATION
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)\deployments\azuredeploy.json'
              csmParametersFile: '$(Pipeline.Workspace)\deployments\azuredeploy.parameters.json'
              deploymentMode: 'Complete'     


