trigger:
- master


stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: build_Virginia
    variables:
    - group: prod-variables
    - name: job_name
      value: 'Build us-east-1'
    steps:
      - script: |
          echo $(job_name)
          echo $SERVICECONNECTION
        displayName: 'Show Variable Values'


  - job: Build
    variables:
      - group: prod-variables
    displayName: Build
    pool:
      vmImage: $vmImageName

    steps:
    - task: CopyFiles@2
      displayName: 'Publish ARM templates'
      inputs:
        SourceFolder: 'MyDemo.Deployments'
        Contents: '**\*.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)\deployments'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: "$workingDirectory\\*.csproj"
        arguments: --output $(System.DefaultWorkingDirectory)\publish_output --configuration Release

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)\publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)\$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)\deployments'
      artifact: deployments

    - publish: '$(Build.ArtifactStagingDirectory)\$(Build.BuildId).zip'
      artifact: drop
